### ISSUE TITLE
[Certificate Password Recovery]

### ISSUE THREAD

**Issue by jparnell8839** [boredwookie/tools#1]
I tried to comment on your blog, but it seems you've disabled comments (cant say I blame you, lots of spammy comments out there). I wish I had known about your github, otherwise I would have just forked it from here rather than downloading it from your site.

I took your recovery tool and made a couple changes (after Windows decided to restart for updates while it was running):

1. Added exit logging to save all input fields and the last failed password attempt into a log file in the exe path using the Application.ApplicationExit event
2. Added a restore inputs on Application.OnLoad events to pick up where it left off

The code is messy at best, but it works - I'm still new to .Net development, and haven't figured out all the kinks and mannerisms.

**Comment by boredwookie** [comment]
The GitHub is kind of new, I'm still getting everything moved over. :)

Sounds like you've made a pretty useful change (especially given non-deterministic Windows 10 updates!). If you have the revised version up somewhere you can post a link to it here.

**Comment by jparnell8839** [comment]
I have it hosted at https://github.com/jparnell8839/Certificate-Password-Recovery . I gave you credit and links in the readme, and retained the original MIT license - the only thing I changed in the readme was the version of Visual Studio used, and the original build target (4.5.2 instead of 4.0).

If you want to download the sources and host it on your github (after any changes you'd like to make, I'd be lying if I said it was the neatest code out there), I'd be happy to remove my repo and do the fork from yours, that way we can maintain realism as to who actually owns it

**Comment by boredwookie** [comment]
I have no problems the way you are hosting it- It's been years since I've really done anything with the code at this point (moved on to other projects) :)

Since my 'tools' repo is full of a bunch of other stuff it probably doesn't make the most sense to fork it (too much baggage).
